[profile.default]
src = 'src'
test = 'tests'
script = 'scripts'
out = 'out'
libs = ['lib']
remappings = [
    'forge-std/=lib/forge-std/src/',
    'aave-address-book/=lib/aave-address-book/src/',
]

[rpc_endpoints]
ethereum="${RPC_ETHEREUM}"

# See more config options https://github.com/gakonst/foundry/tree/master/config
